version: '2'

services:
    code:
        image: busybox
        command: /bin/true
        volumes:
            - ../code:/var/www
    php-cli:
        build:
            context: ./php-cli
        container_name: php-cli
        volumes_from:
                - code
